version: 2
updates:
  - package-ecosystem: 'pip'
    directory: '/'
    schedule:
      interval: 'weekly'
      day: 'saturday'
    labels:
      - 'python'
  - package-ecosystem: 'docker'
    directory: '/'
    schedule:
      interval: 'weekly'
      day: 'saturday'
    labels:
      - 'docker'
  - package-ecosystem: 'npm'
    directory: 'docs/'
    schedule:
      interval: 'weekly'
      day: 'saturday'
    labels:
      - 'node'
