version: 2
updates:
  - package-ecosystem: 'gomod'
    directory: '/'
    schedule:
      interval: 'weekly'
      day: 'saturday'
    labels:
      - 'go'
      - 'dependencies'
  - package-ecosystem: 'docker'
    directory: '/'
    schedule:
      interval: 'weekly'
      day: 'saturday'
    labels:
      - 'docker'
      - 'dependencies'
