name: Deploy Application

on:
  push:
    branches:
      - 'main'
    paths:
      - 'go.mod'
      - 'go.sum'
      - 'bot.go'
      - 'Dockerfile'

jobs:
  build_and_push:
    name: Build and Push Container Image
    runs-on: ubuntu-22.04
    permissions:
      contents: 'read'
      id-token: 'write'
    steps:
    - name: Checkout
      uses: actions/checkout@v3
    - name: GCP Auth
      uses: 'google-github-actions/auth@v1'
      with:
        workload_identity_provider: ${{ secrets.GCP_WORKLOAD_IDENTITY_PROVIDER }}
        service_account: ${{ secrets.GCP_SERVICE_ACCOUNT }}
    - name: 'GCP gcloud Setup'
      uses: 'google-github-actions/setup-gcloud@v3'
    - name: Configure GAR
      run: |
        gcloud auth configure-docker us-central1-docker.pkg.dev
    - name: Build
      run: |
        docker build -t us-central1-docker.pkg.dev/jcdk-capture-twitter-bot/jcdk-capture-twitter-bot/bot:latest .
    - name: Push
      run: |
        docker push us-central1-docker.pkg.dev/jcdk-capture-twitter-bot/jcdk-capture-twitter-bot/bot:latest
